import { StyleSheet } from "react-native";
import { COLORS, FONT_SIZES, SPACING } from "../../constants/theme";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    header: {
        fontSize: FONT_SIZES.large,
        fontWeight: "600",
        color: COLORS.textPrimary,
        marginTop: SPACING.md,
        marginLeft: SPACING.md,
        marginBottom: SPACING.sm,
    },
    title: {
        fontSize: FONT_SIZES.large,
        fontWeight: "600",
        color: COLORS.textPrimary,
        marginTop: SPACING.md,
        marginLeft: SPACING.md,
        marginBottom: SPACING.sm,
    },
    row: {
        flexDirection: "row",
        paddingVertical: SPACING.sm,
        borderBottomWidth: 1,
        borderColor: COLORS.border,
        paddingHorizontal: SPACING.md,
    },
    info: { flex: 1 },
    name: { fontSize: FONT_SIZES.medium, color: COLORS.textPrimary },
    finished: { textDecorationLine: "line-through", color: COLORS.textSecondary },
    desc: { color: COLORS.textSecondary },
    meta: { color: COLORS.textSecondary, marginTop: SPACING.sm },
    actions: { justifyContent: "center", alignItems: "center" },
    deleteBtn: {
        marginTop: SPACING.sm,
        paddingHorizontal: 10,
        paddingVertical: 6,
        backgroundColor: "#ff3b30",
        borderRadius: 6,
    },
    deleteTxt: { color: "#fff" },
    empty: { textAlign: "center", marginTop: SPACING.lg, color: COLORS.border },
    form: {
        marginTop: SPACING.md,
        borderTopWidth: 1,
        borderColor: COLORS.border,
        paddingTop: SPACING.md,
        paddingHorizontal: SPACING.md,
    },
    formTitle: { fontWeight: "600", marginBottom: SPACING.sm },
    input: {
        borderWidth: 1,
        borderColor: COLORS.border,
        padding: SPACING.sm,
        borderRadius: 6,
        marginBottom: SPACING.sm,
        backgroundColor: COLORS.white,
    },
    textarea: { minHeight: 60, textAlignVertical: "top" },
    formLabel: { marginBottom: SPACING.sm, color: COLORS.textPrimary },
    listChip: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: "#f0f0f0",
        borderRadius: 20,
        marginRight: 8,
    },
    listChipActive: { backgroundColor: "#007aff" },
    listChipText: { color: "#000" },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: SPACING.md,
    },
    modalContent: {
        width: '100%',
        maxWidth: 600,
        backgroundColor: COLORS.white,
        borderRadius: 8,
        padding: SPACING.md,
    },
    modalHeader: {
        fontSize: FONT_SIZES.large,
        fontWeight: '700',
        color: COLORS.textPrimary,
        marginBottom: SPACING.sm,
    },
    modalListItem: {
        paddingVertical: SPACING.sm,
        paddingHorizontal: SPACING.sm,
        borderBottomWidth: 1,
        borderColor: COLORS.border,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    modalListItemText: {
        color: COLORS.textPrimary,
        fontSize: FONT_SIZES.medium,
    },
    modalListColor: {
        width: 16,
        height: 16,
        borderRadius: 4,
        marginRight: SPACING.md,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
});
